augment: true
batch_size: 16
crop_size: 64
ema_decay: 0.999
epochs: 200
lr: 0.0002
min_lr: 1.0e-06
num_blocks: 12
output_dir: checkpoints/v2_deeper_multiloss
synthetic_ratio: 0.7
uncertainty: false
use_cutblur: true
use_fft: true
use_forward: false
use_gradient: true
use_lpips: false
use_msssim: true
use_nll: false
w_charb: 1.0
w_fft: 0.1
w_forward: 0.1
w_grad: 0.1
w_lpips: 0.1
w_msssim: 0.1
w_nll: 1.0
weight_decay: 0.0001
width: 64
